In [1]:
import numpy as np

# List Vs Numpy Array

In [2]:
x = [5,6,4,7,9,9,5,'hi','hey',12.44]

In [3]:
x

[5, 6, 4, 7, 9, 9, 5, 'hi', 'hey', 12.44]

In [4]:
np.array([3,4,6,7,8,3])

array([3, 4, 6, 7, 8, 3])

In [5]:
np.array([3,5,8,8,5,12.55])

array([ 3.  ,  5.  ,  8.  ,  8.  ,  5.  , 12.55])

In [6]:
np.array([3,5,8,8,5,12.55,'hi'])

array(['3', '5', '8', '8', '5', '12.55', 'hi'], dtype='<U32')

In [7]:
np.array([3,5,8,8,5,12.55,True])

array([ 3.  ,  5.  ,  8.  ,  8.  ,  5.  , 12.55,  1.  ])

In [8]:
np.array([3,5,8,8,5,12.55,True,'hi'])

array(['3', '5', '8', '8', '5', '12.55', 'True', 'hi'], dtype='<U32')

In [9]:
import sys

In [10]:
sys.getsizeof(list())

64

In [12]:
sys.getsizeof(np.array([]))

96

In [13]:
size = list(range(1,10000))

In [16]:
sys.getsizeof([1,2,3,4,5,6,23,45,67,2,5,7,8,5,5,4,12])

200

In [17]:
sys.getsizeof(np.array([1,2,3,4,5,6,23,45,67,2,5,7,8,5,5,4,12]))

164

In [18]:
sys.getsizeof(size)

90096

In [19]:
sys.getsizeof(np.array(size))

40092

In [20]:
x = [[4,5,6,7],[3,4,2,1],[7,6,5,8]]

In [21]:
x

[[4, 5, 6, 7], [3, 4, 2, 1], [7, 6, 5, 8]]

In [22]:
x1 = np.array(x)

In [23]:
x1

array([[4, 5, 6, 7],
       [3, 4, 2, 1],
       [7, 6, 5, 8]])