In [1]:
import numpy as np

# Ways to create array

In [2]:
# First method
x= np.array([4,5,6,3,7,8,6,7,5,4])

In [3]:
x

array([4, 5, 6, 3, 7, 8, 6, 7, 5, 4])

In [4]:
x[0]

4

In [5]:
x[-1]

4

In [6]:
x[0:3]

array([4, 5, 6])

In [7]:
# Second method
x1 = np.arange(1,20)

In [8]:
x1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [9]:
x1 = np.arange(2,200,2)

In [11]:
print(x1)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198]


In [12]:
# Third method
np.zeros(4)

array([0., 0., 0., 0.])

In [13]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# Fourth method
# np.linspace(2,20)
np.linspace(2,20,30,retstep=True)

(array([ 2.        ,  2.62068966,  3.24137931,  3.86206897,  4.48275862,
         5.10344828,  5.72413793,  6.34482759,  6.96551724,  7.5862069 ,
         8.20689655,  8.82758621,  9.44827586, 10.06896552, 10.68965517,
        11.31034483, 11.93103448, 12.55172414, 13.17241379, 13.79310345,
        14.4137931 , 15.03448276, 15.65517241, 16.27586207, 16.89655172,
        17.51724138, 18.13793103, 18.75862069, 19.37931034, 20.        ]),
 0.6206896551724138)

In [19]:
np.random.random()

0.33763061322161825

In [20]:
# fifth method
np.random.random(size=(4,4))

array([[0.67251497, 0.31087183, 0.50821857, 0.45597764],
       [0.78210677, 0.98623413, 0.49709762, 0.20547321],
       [0.79029388, 0.96400372, 0.70854784, 0.85537893],
       [0.50937599, 0.32670406, 0.1296018 , 0.888894  ]])

In [21]:
np.random.randn()

-0.8078032101492644

In [22]:
np.random.randn(4,4)

array([[-0.6426526 , -1.40768765, -2.28338756, -1.92427723],
       [-2.68550943, -0.77593451, -0.42672527, -0.504245  ],
       [-1.25368188, -0.04708762, -0.24547363, -0.7219967 ],
       [ 0.5595346 , -0.54266305,  1.59750111,  0.00298381]])

In [25]:
np.random.randint(10,100)

85

In [26]:
# it will return 20 random numbers in range of 10 an 1000
np.random.randint(10,1000,20)

array([123, 926,  77, 208, 488, 981, 543, 841, 136,  47, 508, 998,  41,
       649, 237, 467,  72,  75, 218, 616])

# Slicing Numpy Arrays

In [28]:
arr = np.array([[5,4,6,4],[7,8,6,3],[3,2,6,7],[4,8,7,9]])

In [29]:
arr

array([[5, 4, 6, 4],
       [7, 8, 6, 3],
       [3, 2, 6, 7],
       [4, 8, 7, 9]])

In [30]:
arr[0]

array([5, 4, 6, 4])

In [31]:
arr[0][0]

5

In [32]:
arr[0:2]

array([[5, 4, 6, 4],
       [7, 8, 6, 3]])

In [34]:
arr[:,0]

array([5, 7, 3, 4])

In [35]:
arr

array([[5, 4, 6, 4],
       [7, 8, 6, 3],
       [3, 2, 6, 7],
       [4, 8, 7, 9]])

In [36]:
arr[0:2,0:2]

array([[5, 4],
       [7, 8]])

In [37]:
arr[2:4,2:4]

array([[6, 7],
       [7, 9]])

# Array Methods

In [38]:
data = np.random.randint(10,1000,20)

In [39]:
data

array([845, 679, 655, 326, 739, 900, 111, 994, 140, 609, 275, 793, 160,
       276, 754,  61, 473, 501, 884,  25])

In [40]:
data.min()

25

In [41]:
data.max()

994

In [42]:
sorted(data)

[25,
 61,
 111,
 140,
 160,
 275,
 276,
 326,
 473,
 501,
 609,
 655,
 679,
 739,
 754,
 793,
 845,
 884,
 900,
 994]

In [43]:
data.argmin()

19

In [44]:
data.argmax()

7

In [45]:
data[19]

25

In [46]:
data[7]

994

In [47]:
data.argsort()

array([19, 15,  6,  8, 12, 10, 13,  3, 16, 17,  9,  2,  1,  4, 14, 11,  0,
       18,  5,  7], dtype=int64)

In [48]:
np.zeros_like(data)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
np.ones_like(data)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [50]:
x = np.random.random((5,5))

In [52]:
x

array([[0.47607209, 0.47336544, 0.36300014, 0.28942359, 0.813416  ],
       [0.84219549, 0.25572279, 0.70170514, 0.11970945, 0.41519952],
       [0.45462927, 0.72922149, 0.51394657, 0.04088741, 0.68979082],
       [0.87158707, 0.90572473, 0.92219185, 0.97774741, 0.09210738],
       [0.61564303, 0.66238724, 0.84557238, 0.97084208, 0.7062101 ]])

In [53]:
np.zeros_like(x)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
np.shape(x)

(5, 5)

In [55]:
np.ndim(x)

2